apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openmarkers-postgres
  namespace: openmarkers
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-system-trixie
  bootstrap:
    initdb:
      database: openmarkers
      owner: openmarkers
      secret:
        name: openmarkers-postgres-owner
  storage:
    storageClass: local-path
    size: 2Gi
  backup:
    barmanObjectStore:
      serverName: openmarkers-postgres-pg18
      destinationPath: "s3://cnpg-backups/openmarkers-postgres"
      endpointURL: "http://10.77.77.190:9000"
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-s3
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
