apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openmarkers-postgres-owner
  namespace: openmarkers
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openmarkers-postgres-owner
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: openmarkers-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: openmarkers-postgres
        property: password
