apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openmarkers-env
  namespace: openmarkers
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openmarkers-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: 'postgres://{{ .username }}:{{ .password }}@openmarkers-postgres-rw.openmarkers.svc.cluster.local:5432/openmarkers'
        ANTHROPIC_API_KEY: '{{ .anthropicApiKey }}'
        AUTH_SERVICE_CLIENT_ID: '{{ .authServiceClientId }}'
        AUTH_SERVICE_CLIENT_SECRET: '{{ .authServiceClientSecret }}'
  data:
    - secretKey: username
      remoteRef:
        key: openmarkers-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: openmarkers-postgres
        property: password
    - secretKey: anthropicApiKey
      remoteRef:
        key: openmarkers
        property: ANTHROPIC_API_KEY
    - secretKey: authServiceClientId
      remoteRef:
        key: openmarkers
        property: AUTH_SERVICE_CLIENT_ID
    - secretKey: authServiceClientSecret
      remoteRef:
        key: openmarkers
        property: AUTH_SERVICE_CLIENT_SECRET
