---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: openmarkers
  namespace: openmarkers
spec:
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
  image: ghcr.io/nezdemkovski/openmarkers
  interval: 15m0s
