---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  deletionPolicy: Orphan
  dependsOn:
  - name: external-secrets
  interval: 10m0s
  path: ./infrastructure/onepassword-connect
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
