---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plausible-reader
  namespace: flux-system
spec:
  deletionPolicy: Orphan
  dependsOn:
  - name: plausible
  interval: 10m0s
  path: ./apps/plausible/reader
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  suspend: true
  timeout: 5m0s
  wait: true
