---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: supabase
  namespace: flux-system
spec:
  deletionPolicy: Orphan
  dependsOn:
  - name: onepassword-store
  interval: 10m0s
  path: ./apps/supabase
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
