apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgres.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1
  imageName: {{ .Values.postgres.imageName }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.owner }}
      secret:
        name: openmarkers-postgres-owner
  storage:
    storageClass: {{ .Values.postgres.storage.storageClass }}
    size: {{ .Values.postgres.storage.size }}
