apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://charts.containeroo.ch
    chart: local-path-provisioner
    targetRevision: 0.0.37
    helm:
      valuesObject:
        storageClass:
          create: true
          name: local-path
          defaultClass: true
          reclaimPolicy: Retain
          volumeBindingMode: WaitForFirstConsumer
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /var/lib/local-path-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
