apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr-flux
  namespace: homarr-flux
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: homarr
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/homarr-labs/homarr
      tag: v1.77.2 # {"$imagepolicy": "flux-system:homarr-flux-app:tag"}
    env:
      TZ: Europe/Prague
    envSecrets:
      dbEncryption:
        existingSecret: homarr-env
        key: SECRET_ENCRYPTION_KEY
    persistence:
      homarrDatabase:
        enabled: true
        name: homarr-flux-database
        storageClassName: local-path
        size: 1Gi
    strategyType: Recreate
    service:
      type: ClusterIP
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: PersistentVolumeClaim
              name: homarr-flux-database
            patch: |-
              - op: add
                path: /metadata/annotations
                value:
                  helm.sh/resource-policy: keep
