apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmarkers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/nezdemkovski/homelab-gitops.git
    targetRevision: master
    path: charts/openmarkers-stack
    helm:
      releaseName: openmarkers
  destination:
    server: https://kubernetes.default.svc
    namespace: openmarkers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
