apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fnpc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: ghcr.io/nezdemkovski/charts
    chart: fnpc
    targetRevision: 0.1.8
    helm:
      releaseName: fnpc
  destination:
    server: https://kubernetes.default.svc
    namespace: fnpc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
