apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fnpc-postgres
  namespace: fnpc
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/sync-wave: "3"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.10-system-trixie
  bootstrap:
    initdb:
      database: fnpc
      owner: fnpc
      secret:
        name: fnpc-postgres-owner
  storage:
    storageClass: local-path
    size: 5Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backups/fnpc-postgres"
      endpointURL: "http://10.77.77.190:9000"
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-s3
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: "30d"
