apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fnpc-postgres-owner
  namespace: fnpc
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: fnpc-postgres-owner
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: fnpc-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: fnpc-postgres
        property: password
