apiVersion: v1
kind: Service
metadata:
  name: nocodb-postgres
  namespace: nocodb
spec:
  selector:
    app.kubernetes.io/name: nocodb-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
