apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amela.io
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: amela.io
  sources:
    - repoURL: ghcr.io/amela-io/charts
      chart: amela-backend
      targetRevision: 0.1.9
      helm:
        releaseName: amela-backend
        values: |
          fullnameOverride: amela-backend
          image:
            repository: ghcr.io/amela-io/backend
            tag: "0.1.9"
            digest: sha256:4d6be6680afb981d430512942484a7a6a3011704fae2358b6b75b27a67da54e5
          imagePullSecrets:
            - name: amela-ghcr
          envSecretName: amela-backend-env
    - repoURL: ghcr.io/amela-io/charts
      chart: amela-application
      targetRevision: 0.1.11
      helm:
        releaseName: amela-application
        values: |
          fullnameOverride: amela-application
          image:
            repository: ghcr.io/amela-io/application
            tag: "0.1.11"
            digest: sha256:e8d80910e434862ea3db6f29801b0766cb0a6cfbf7bf714940d8706883920cb2
          imagePullSecrets:
            - name: amela-ghcr
  destination:
    server: https://kubernetes.default.svc
    namespace: amela
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
