apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amela.io
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: amela.io
  sources:
    - repoURL: ghcr.io/amela-io/charts
      chart: amela-backend
      targetRevision: 0.1.3
      helm:
        releaseName: amela-backend
        values: |
          fullnameOverride: amela-backend
          image:
            repository: ghcr.io/amela-io/backend
            tag: "0.1.3"
          imagePullSecrets:
            - name: amela-ghcr
          envSecretName: amela-backend-env
    - repoURL: ghcr.io/amela-io/charts
      chart: amela-application
      targetRevision: 0.1.2
      helm:
        releaseName: amela-application
        values: |
          fullnameOverride: amela-application
          image:
            repository: ghcr.io/amela-io/application
            tag: "0.1.2"
          imagePullSecrets:
            - name: amela-ghcr
  destination:
    server: https://kubernetes.default.svc
    namespace: amela
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
