apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: amela-ghcr-repository
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: amela-ghcr-repository
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: helm
        enableOCI: "true"
        name: amela-charts
        url: ghcr.io/amela-io/charts
        username: '{{ .username }}'
        password: '{{ .token }}'
  data:
    - secretKey: username
      remoteRef: {key: amela-ghcr, property: username}
    - secretKey: token
      remoteRef: {key: amela-ghcr, property: password}
