apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: amela-ghcr
  namespace: amela
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: amela-ghcr
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .token }}","auth":"{{ printf "%s:%s" .username .token | b64enc }}"}}}'
  data:
    - secretKey: username
      remoteRef: {key: amela-ghcr, property: username}
    - secretKey: token
      remoteRef: {key: amela-ghcr, property: password}
