apiVersion: v1
kind: Namespace
metadata:
  name: amela
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app.kubernetes.io/part-of: amela
