apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: haymaker-env
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: haymaker-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: 'postgres://{{ `{{ .dbUsername | urlquery }}` }}:{{ `{{ .dbPassword | urlquery }}` }}@{{ .Values.postgres.clusterName }}-rw.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.postgres.database }}'
        HAYMAKER_FIGHT_SECRET_KEY: '{{ `{{ .fightSecretKey }}` }}'
        PLAUSIBLE_STATS_API_KEY: '{{ `{{ .plausibleStatsApiKey }}` }}'
        PLAUSIBLE_BASE_URL: '{{ `{{ .plausibleBaseUrl }}` }}'
        PLAUSIBLE_SITE_ID: '{{ `{{ .plausibleSiteId }}` }}'
  data:
    - secretKey: dbUsername
      remoteRef:
        key: {{ .Values.onepassword.postgresItem }}
        property: username
    - secretKey: dbPassword
      remoteRef:
        key: {{ .Values.onepassword.postgresItem }}
        property: password
    - secretKey: fightSecretKey
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: HAYMAKER_FIGHT_SECRET_KEY
    - secretKey: plausibleStatsApiKey
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: PLAUSIBLE_STATS_API_KEY
    - secretKey: plausibleBaseUrl
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: PLAUSIBLE_BASE_URL
    - secretKey: plausibleSiteId
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: PLAUSIBLE_SITE_ID
