apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-env
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: auth-env
    creationPolicy: Owner
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: BETTER_AUTH_SECRET
    - secretKey: AUTH_PROJECTS
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: AUTH_PROJECTS
    {{- if eq .Values.env.email.provider "cloudflare" }}
    - secretKey: CLOUDFLARE_EMAIL_API_TOKEN
      remoteRef:
        key: {{ .Values.onepassword.appItem }}
        property: {{ .Values.onepassword.cloudflareEmailApiTokenProperty }}
    {{- end }}
