{{- if .Values.redis.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redis.fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ .Values.redis.fullname }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        REDIS_PASSWORD: "{{ `{{ .password }}` }}"
        REDIS_URL: redis://default:{{ `{{ .password }}` }}@{{ .Values.redis.fullname }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.redis.service.port }}
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.onepassword.redisItem }}
        property: {{ .Values.onepassword.redisPasswordProperty }}
{{- end }}
