{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  REDIS_URL: {{ printf "redis://default:%s@%s.%s.svc.cluster.local:%v" .Values.redis.auth.password .Values.redis.fullname .Release.Namespace .Values.redis.service.port | quote }}
{{- end }}
