apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-postgres-cnpg
  namespace: n8n
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.10-system-trixie
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-cnpg-app
  storage:
    storageClass: local-path
    size: 5Gi
  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backups/n8n-postgres-cnpg"
      endpointURL: "http://10.77.77.190:9000"
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-s3
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
