apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-backup-secret.yaml
  - cnpg-app-secret.yaml
  - external-secret.yaml
  - pvc.yaml
  - cnpg-cluster.yaml
  - cnpg-scheduled-backup.yaml
  - oci-repository.yaml
  - helm-release.yaml
  - image-automation.yaml
