apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: amela-rustfs-egress
  namespace: amela
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.77.77.190/32
      ports:
        - protocol: TCP
          port: 9000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: amela-media-rustfs-egress
  namespace: cloudflared
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.77.77.190/32
      ports:
        - protocol: TCP
          port: 9000
