apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - amela-rustfs-egress.yaml
  - clusterwide-common.yaml
  - cilium-kube-apiserver-egress.yaml
  - cnpg-backup-egress.yaml
  - cnpg-operator-ingress.yaml
  - workload-baseline.yaml
  - workload-haymaker.yaml
