server:
  replicaCount: 1
  image:
    repository: awinterstein/habitica-server
    tag: "5.47.9"
    pullPolicy: IfNotPresent
  baseUrl: https://habits.nezdemkovski.cloud
  inviteOnly: false
  adminEmail: yuri@nezdemkovski.com
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 90
    periodSeconds: 30

mongo:
  image:
    repository: mongo
    tag: "4.4.30"
    pullPolicy: IfNotPresent
  replicaSetName: rs
  service:
    port: 27017
  storage:
    className: local-path
    dataSize: 10Gi
    configSize: 1Gi
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
