apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-postgres-env
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-postgres-env
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: n8n/DB_POSTGRESDB_DATABASE
    - secretKey: POSTGRES_USER
      remoteRef:
        key: n8n/DB_POSTGRESDB_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: n8n/DB_POSTGRESDB_PASSWORD

