apiVersion: v1
kind: Service
metadata:
  name: habitica-mongo
  namespace: habitica
  labels:
    app.kubernetes.io/name: habitica-mongo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: habitica-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
