apiVersion: v1
kind: Service
metadata:
  name: habitica
  namespace: habitica
  labels:
    app.kubernetes.io/name: habitica
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: habitica
  ports:
    - name: http
      port: 80
      targetPort: http
