apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-env
  namespace: homarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homarr-env
    creationPolicy: Owner
  data:
    - secretKey: SECRET_ENCRYPTION_KEY
      remoteRef:
        key: homarr/SECRET_ENCRYPTION_KEY

