apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-telegram-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: flux-telegram-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: homelab-fluxcd
        property: TELEGRAM_BOT_TOKEN
