---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: telegram
  namespace: flux-system
spec:
  channel: "1952378"
  secretRef:
    name: flux-telegram-token
  type: telegram
