apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-secrets
  namespace: supabase
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: supabase-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        anonKey: '{{ .anonKey }}'
        serviceKey: '{{ .serviceKey }}'
        jwtSecret: '{{ .jwtSecret }}'
        dbPassword: '{{ .dbPassword }}'
        dbPasswordEncoded: '{{ .dbPassword | urlquery }}'
        database: postgres
        dashboardUsername: '{{ .dashboardUsername }}'
        dashboardPassword: '{{ .dashboardPassword }}'
        dashboardOpenAiApiKey: ""
        smtpUsername: '{{ .smtpUsername }}'
        smtpPassword: '{{ .smtpPassword }}'
        realtimeSecretKeyBase: '{{ .realtimeSecretKeyBase }}'
        realtimeDbEncKey: '{{ .realtimeDbEncKey }}'
        metaCryptoKey: '{{ .metaCryptoKey }}'
        analyticsPublicToken: '{{ .analyticsPublicToken }}'
        analyticsPrivateToken: '{{ .analyticsPrivateToken }}'
        s3KeyId: '{{ .s3KeyId }}'
        s3AccessKey: '{{ .s3AccessKey }}'
  data:
    - secretKey: anonKey
      remoteRef: {key: supabase, property: ANON_KEY}
    - secretKey: serviceKey
      remoteRef: {key: supabase, property: SERVICE_KEY}
    - secretKey: jwtSecret
      remoteRef: {key: supabase, property: JWT_SECRET}
    - secretKey: dbPassword
      remoteRef: {key: supabase, property: DB_PASSWORD}
    - secretKey: dashboardUsername
      remoteRef: {key: supabase, property: DASHBOARD_USERNAME}
    - secretKey: dashboardPassword
      remoteRef: {key: supabase, property: DASHBOARD_PASSWORD}
    - secretKey: smtpUsername
      remoteRef: {key: supabase, property: SMTP_USERNAME}
    - secretKey: smtpPassword
      remoteRef: {key: supabase, property: SMTP_PASSWORD}
    - secretKey: realtimeSecretKeyBase
      remoteRef: {key: supabase, property: REALTIME_SECRET_KEY_BASE}
    - secretKey: realtimeDbEncKey
      remoteRef: {key: supabase, property: REALTIME_DB_ENC_KEY}
    - secretKey: metaCryptoKey
      remoteRef: {key: supabase, property: META_CRYPTO_KEY}
    - secretKey: analyticsPublicToken
      remoteRef: {key: supabase, property: ANALYTICS_PUBLIC_TOKEN}
    - secretKey: analyticsPrivateToken
      remoteRef: {key: supabase, property: ANALYTICS_PRIVATE_TOKEN}
    - secretKey: s3KeyId
      remoteRef: {key: supabase, property: S3_KEY_ID}
    - secretKey: s3AccessKey
      remoteRef: {key: supabase, property: S3_ACCESS_KEY}
