apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  ignoreDifferences:
    - kind: Secret
      namespace: kube-system
      name: cilium-ca
      jsonPointers:
        - /data
    - kind: Secret
      namespace: kube-system
      name: hubble-relay-client-certs
      jsonPointers:
        - /data
    - kind: Secret
      namespace: kube-system
      name: hubble-server-certs
      jsonPointers:
        - /data
  source:
    repoURL: https://helm.cilium.io
    chart: cilium
    targetRevision: 1.19.5
    helm:
      valuesObject:
        ipam:
          mode: kubernetes
        kubeProxyReplacement: false
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
            cleanCiliumState:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
        operator:
          replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
