apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: haymaker-env
  namespace: haymaker
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: haymaker-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: 'postgres://{{ .dbUsername | urlquery }}:{{ .dbPassword | urlquery }}@haymaker-postgres-rw.haymaker.svc.cluster.local:5432/haymaker'
        HAYMAKER_FIGHT_SECRET_KEY: '{{ .fightSecretKey }}'
        PLAUSIBLE_STATS_API_KEY: '{{ .plausibleStatsApiKey }}'
        PLAUSIBLE_BASE_URL: '{{ .plausibleBaseUrl }}'
        PLAUSIBLE_SITE_ID: '{{ .plausibleSiteId }}'
  data:
    - secretKey: dbUsername
      remoteRef:
        key: haymaker-postgres
        property: username
    - secretKey: dbPassword
      remoteRef:
        key: haymaker-postgres
        property: password
    - secretKey: fightSecretKey
      remoteRef:
        key: haymaker
        property: HAYMAKER_FIGHT_SECRET_KEY
    - secretKey: plausibleStatsApiKey
      remoteRef:
        key: haymaker
        property: PLAUSIBLE_STATS_API_KEY
    - secretKey: plausibleBaseUrl
      remoteRef:
        key: haymaker
        property: PLAUSIBLE_BASE_URL
    - secretKey: plausibleSiteId
      remoteRef:
        key: haymaker
        property: PLAUSIBLE_SITE_ID
