---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: haymaker-api
  namespace: haymaker
spec:
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
  image: ghcr.io/nezdemkovski/haymaker
  interval: 15m0s
  secretRef:
    name: haymaker-ghcr
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: haymaker-frontend
  namespace: haymaker
spec:
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
  image: ghcr.io/nezdemkovski/haymaker-frontend
  interval: 15m0s
  secretRef:
    name: haymaker-ghcr
