---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: haymaker-api
  namespace: haymaker
spec:
  image: ghcr.io/nezdemkovski/haymaker
  interval: 15m0s
  secretRef:
    name: haymaker-ghcr
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: haymaker-api
  namespace: haymaker
spec:
  digestReflectionPolicy: Always
  imageRepositoryRef:
    name: haymaker-api
  interval: 15m0s
  policy:
    semver:
      range: '>=0.3.0 <0.4.0'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: haymaker-frontend
  namespace: haymaker
spec:
  image: ghcr.io/nezdemkovski/haymaker-frontend
  interval: 15m0s
  secretRef:
    name: haymaker-ghcr
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: haymaker-frontend
  namespace: haymaker
spec:
  digestReflectionPolicy: Always
  imageRepositoryRef:
    name: haymaker-frontend
  interval: 15m0s
  policy:
    semver:
      range: '>=0.3.0 <0.4.0'
