apiVersion: v2
name: monitoring
description: Homelab monitoring stack with Grafana and Prometheus
type: application
version: 0.1.1
dependencies:
  - name: kube-prometheus-stack
    version: 88.2.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 12.10.4
    repository: https://grafana-community.github.io/helm-charts
  - name: grafana-mcp
    version: 0.20.0
    repository: https://grafana-community.github.io/helm-charts
