---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
  image: cloudflare/cloudflared
  interval: 15m0s
