apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plausible-env
  namespace: plausible
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plausible-env
    creationPolicy: Owner
  data:
    - secretKey: BASE_URL
      remoteRef:
        key: plausible/BASE_URL
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: plausible/SECRET_KEY_BASE
    - secretKey: TOTP_VAULT_KEY
      remoteRef:
        key: plausible/TOTP_VAULT_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: plausible/DATABASE_URL
    - secretKey: CLICKHOUSE_DATABASE_URL
      remoteRef:
        key: plausible/CLICKHOUSE_DATABASE_URL
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: plausible/POSTGRES_PASSWORD
    - secretKey: CLICKHOUSE_PASSWORD
      remoteRef:
        key: plausible/CLICKHOUSE_PASSWORD
