apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nezdemos-grafana-reader
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nezdemos-grafana-reader
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.onepassword.grafanaReaderItem }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.onepassword.grafanaReaderItem }}
        property: password
