apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgres.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1
  imageName: {{ .Values.postgres.imageName }}
  managed:
    roles:
      - name: {{ .Values.postgres.owner }}
        ensure: present
        login: true
        passwordSecret:
          name: nezdemos-postgres-owner
      - name: whoop_scraper
        ensure: present
        login: true
        passwordSecret:
          name: whoop-scraper-db
  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.owner }}
      secret:
        name: nezdemos-postgres-owner
  storage:
    storageClass: {{ .Values.postgres.storage.storageClass }}
    size: {{ .Values.postgres.storage.size }}
