apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgres.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: 1
  imageName: {{ .Values.postgres.imageName }}
  managed:
    roles:
      - name: {{ .Values.postgres.owner }}
        ensure: present
        login: true
        passwordSecret:
          name: nezdemos-postgres-owner
      - name: whoop_scraper
        ensure: present
        login: true
        passwordSecret:
          name: whoop-scraper-db
      - name: grafana_reader
        ensure: present
        login: true
        passwordSecret:
          name: nezdemos-grafana-reader
      - name: nezdemos_api
        ensure: present
        login: true
        passwordSecret:
          name: nezdemos-api-env
  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.owner }}
      secret:
        name: nezdemos-postgres-owner
  storage:
    storageClass: {{ .Values.postgres.storage.storageClass }}
    size: {{ .Values.postgres.storage.size }}
{{- if .Values.postgres.backup.enabled }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.postgres.backup.destinationPath | quote }}
      endpointURL: {{ .Values.postgres.backup.endpointURL | quote }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.postgres.backup.secretName }}
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: {{ .Values.postgres.backup.secretName }}
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: {{ .Values.postgres.backup.retentionPolicy | quote }}
{{- end }}
