{{- if .Values.postgres.backup.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.postgres.backup.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ .Values.postgres.backup.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.postgres.backup.onepasswordItem }}
        property: RUSTFS_ACCESS_KEY
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: {{ .Values.postgres.backup.onepasswordItem }}
        property: RUSTFS_SECRET_KEY
{{- end }}
