apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whoop-scraper-env
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: whoop-scraper-env
    creationPolicy: Owner
  data:
    - secretKey: WHOOP_DB_PASSWORD
      remoteRef:
        key: {{ .Values.onepassword.whoopItem }}
        property: password
    - secretKey: WHOOP_CLIENT_ID
      remoteRef:
        key: {{ .Values.onepassword.whoopItem }}
        property: WHOOP_CLIENT_ID
    - secretKey: WHOOP_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.onepassword.whoopItem }}
        property: WHOOP_CLIENT_SECRET
    - secretKey: WHOOP_ENCRYPTION_KEY
      remoteRef:
        key: {{ .Values.onepassword.whoopItem }}
        property: WHOOP_ENCRYPTION_KEY
    - secretKey: WHOOP_TOKEN_STORAGE
      remoteRef:
        key: {{ .Values.onepassword.whoopItem }}
        property: WHOOP_TOKEN_STORAGE
