apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.secret.remoteKeyPrefix }}/DB_POSTGRESDB_DATABASE
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.secret.remoteKeyPrefix }}/DB_POSTGRESDB_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.secret.remoteKeyPrefix }}/DB_POSTGRESDB_PASSWORD
