apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n-postgres.fullname" . }}
spec:
  selector:
    {{- include "n8n-postgres.labels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
