---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  chart:
    spec:
      chart: ./charts/uptime-kuma
      interval: 1h0m0s
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1h0m0s
  driftDetection:
    mode: enabled
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  releaseName: uptime-kuma
  storageNamespace: uptime-kuma
  targetNamespace: uptime-kuma
  timeout: 5m
  upgrade:
    cleanupOnFail: true
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
