apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: homarr-flux-chart
  namespace: flux-system
spec:
  image: ghcr.io/homarr-labs/charts/homarr
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: homarr-flux-chart
  namespace: flux-system
spec:
  filterTags:
    extract: $version
    pattern: ^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$
  imageRepositoryRef:
    name: homarr-flux-chart
  policy:
    semver:
      range: ">=8.29.2 <9.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: homarr-flux-app
  namespace: flux-system
spec:
  image: ghcr.io/homarr-labs/homarr
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: homarr-flux-app
  namespace: flux-system
spec:
  filterTags:
    extract: $version
    pattern: ^v(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$
  imageRepositoryRef:
    name: homarr-flux-app
  policy:
    semver:
      range: ">=1.61.0 <2.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: homarr-flux
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "chore(deps): update Flux-managed Homarr versions"
    push:
      branch: master
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    path: ./clusters/homelab/apps/homarr-flux
    strategy: Setters
