apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: ghcr.io/nezdemkovski/charts
    chart: auth
    targetRevision: 0.2.40
    helm:
      releaseName: auth
      values: |
        env:
          autoMigrate: "false"
          trustProxyHeaders: "true"
          publicBaseUrl: https://auth.nezdemkovski.cloud
          adminEmail: yuri@nezdemkovski.com
          redisUrlSecret:
            name: auth-redis
            key: REDIS_URL
          postgresHost: auth-postgres-rw.auth.svc.cluster.local
          postgresPort: "5432"
          postgresDb: auth

        api:
          image:
            tag: v0.1.91
            digest: sha256:0cc4fe62f6e0be48a166a50283b4eb46ca07406d077227918ca2dd353c493eb1

        admin:
          image:
            tag: v0.1.91
            digest: sha256:a9f27642d5585053c629270a4685ab80d9ce4d1270f736436c64de933e37d57e

        login:
          image:
            tag: v0.1.91
            digest: sha256:f3451d4e63b0517f8665bece3deed211255020078aa10a4e32a0b5efbf287088

        router:
          image:
            tag: v0.1.91
            digest: sha256:0ffa05654aa60b00566fdd56b4a6cadcdf5246a42efa027b219478ebcfb12f2a

        postgres:
          credentialsSecret:
            name: auth-postgres-owner
            usernameKey: username
            passwordKey: password

        objectStorage:
          enabled: true
          bucket: auth-public
          region: us-east-1
          storage:
            storageClass: local-path
            size: 5Gi

        onepassword:
          appItem: auth
          redisItem: auth-redis
          redisPasswordProperty: password
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
