apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: ghcr.io/nezdemkovski/charts
    chart: auth
    targetRevision: 0.2.26
    helm:
      releaseName: auth
      values: |
        env:
          autoMigrate: "true"
          trustProxyHeaders: "true"
          publicBaseUrl: https://auth.nezdemkovski.cloud
          adminEmail: yuri@nezdemkovski.com
          redisUrlSecret:
            name: auth-redis
            key: REDIS_URL
          postgresHost: auth-postgres-rw.auth.svc.cluster.local
          postgresPort: "5432"
          postgresDb: auth

        postgres:
          credentialsSecret:
            name: auth-postgres-owner
            usernameKey: username
            passwordKey: password

        objectStorage:
          enabled: true
          bucket: auth-public
          region: us-east-1
          storage:
            storageClass: local-path
            size: 5Gi

        onepassword:
          appItem: auth
          redisItem: auth-redis
          redisPasswordProperty: password
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
