apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: auth-postgres-daily-backup
  namespace: auth
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: auth-postgres
