apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: fb9144ee-d450-448f-94ab-530094b85247
    credentials-file: /etc/cloudflared/credentials/credentials.json
    ingress:
      - hostname: n8n-homelab.nezdemkovski.cloud
        service: http://n8n-main.n8n.svc.cluster.local:5678
      - service: http_status:404

