apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: fb9144ee-d450-448f-94ab-530094b85247
    credentials-file: /etc/cloudflared/credentials/credentials.json
    ingress:
      - hostname: automations.nezdemkovski.cloud
        service: http://n8n-main.n8n.svc.cluster.local:5678
      - hostname: nezdemkovski.cloud
        service: http://homarr.homarr.svc.cluster.local:7575
      - hostname: git.nezdemkovski.cloud
        service: http://forgejo-http.forgejo.svc.cluster.local:3000
      - hostname: habits.nezdemkovski.cloud
        service: http://habitica.habitica.svc.cluster.local:80
      - hostname: analytics.nezdemkovski.cloud
        service: http://plausible.plausible.svc.cluster.local:80
      - hostname: budget.nezdemkovski.cloud
        service: http://actual-budget.actual-budget.svc.cluster.local:80
      - hostname: status.nezdemkovski.cloud
        service: http://uptime-kuma.uptime-kuma.svc.cluster.local:80
      - hostname: argo.nezdemkovski.cloud
        service: https://argocd-server.argocd.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
      - service: http_status:404
