---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  image: code.forgejo.org/forgejo/forgejo
  interval: 15m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: forgejo
  namespace: forgejo
spec:
  filterTags:
    extract: $version
    pattern: ^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)-rootless$
  imageRepositoryRef:
    name: forgejo
  policy:
    semver:
      range: '>=15.0.2 <16.0.0'
