---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
  image: code.forgejo.org/forgejo/forgejo
  interval: 15m0s
