---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 1h0m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  provider: generic
  ref:
    semver: '>=17.1.7 <18.0.0'
  url: oci://codeberg.org/forgejo-contrib/forgejo
