apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cnpg-backup-egress
  namespace: deadair
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/managed-by: cloudnative-pg
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.77.77.190/32
      ports:
        - protocol: TCP
          port: 9000
