apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deadair-cnpg-app
  namespace: deadair
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: deadair-cnpg-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: deadair
        property: DATABASE_USER
    - secretKey: password
      remoteRef:
        key: deadair
        property: DATABASE_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deadair-runtime
  namespace: deadair
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: deadair-runtime
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: deadair
        property: DATABASE_PASSWORD
    - secretKey: KMS_LOCAL_ROOT_KEY
      remoteRef:
        key: deadair
        property: KMS_LOCAL_ROOT_KEY
    - secretKey: AUTHENTICATION_SESSION_JWT_PRIVATE_KEY
      remoteRef:
        key: deadair
        property: AUTHENTICATION_SESSION_JWT_PRIVATE_KEY
