apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-cnpg-app
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-cnpg-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: n8n
        property: DB_POSTGRESDB_USER
    - secretKey: password
      remoteRef:
        key: n8n
        property: DB_POSTGRESDB_PASSWORD
