apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-s3
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cnpg-backup-s3
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: synology-rustfs
        property: RUSTFS_ACCESS_KEY
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: synology-rustfs
        property: RUSTFS_SECRET_KEY
