apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-env
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-env
    creationPolicy: Merge
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: n8n/N8N_ENCRYPTION_KEY
    - secretKey: N8N_HOST
      remoteRef:
        key: n8n/N8N_HOST
    - secretKey: N8N_PORT
      remoteRef:
        key: n8n/N8N_PORT
    - secretKey: N8N_PROTOCOL
      remoteRef:
        key: n8n/N8N_PROTOCOL
    - secretKey: WEBHOOK_URL
      remoteRef:
        key: n8n/WEBHOOK_URL
    - secretKey: N8N_EDITOR_BASE_URL
      remoteRef:
        key: n8n/N8N_EDITOR_BASE_URL
    - secretKey: DB_POSTGRESDB_DATABASE
      remoteRef:
        key: n8n/DB_POSTGRESDB_DATABASE
    - secretKey: DB_POSTGRESDB_USER
      remoteRef:
        key: n8n/DB_POSTGRESDB_USER
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: n8n/DB_POSTGRESDB_PASSWORD
    - secretKey: DB_POSTGRESDB_PORT
      remoteRef:
        key: n8n/DB_POSTGRESDB_PORT
    - secretKey: DB_POSTGRESDB_SCHEMA
      remoteRef:
        key: n8n/DB_POSTGRESDB_SCHEMA
    - secretKey: N8N_RUNNERS_AUTH_TOKEN
      remoteRef:
        key: n8n/N8N_RUNNERS_AUTH_TOKEN
