apiVersion: v1
kind: Service
metadata:
  name: n8n-postgres
  namespace: n8n
spec:
  selector:
    app.kubernetes.io/name: n8n-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres

