apiVersion: v1
kind: Service
metadata:
  name: {{ include "habitica.mongoServiceName" . }}
  labels:
    {{- include "habitica.mongoLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "habitica.mongoLabels" . | nindent 4 }}
  ports:
    - name: mongo
      port: {{ .Values.mongo.service.port }}
      targetPort: mongo
