apiVersion: v1
kind: Service
metadata:
  name: {{ include "habitica.fullname" . }}
  labels:
    {{- include "habitica.serverLabels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "habitica.serverLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
