apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: monitoring
  labels:
    release: monitoring
    app.kubernetes.io/name: argocd-metrics
    app.kubernetes.io/instance: monitoring
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - argocd-metrics
          - argocd-server-metrics
          - argocd-repo-server
          - argocd-applicationset-controller
          - argocd-notifications-controller-metrics
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
