apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "fizzy.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: fizzy
        property: SECRET_KEY_BASE
    - secretKey: MAILER_FROM_ADDRESS
      remoteRef:
        key: fizzy
        property: MAILER_FROM_ADDRESS
    - secretKey: SMTP_ADDRESS
      remoteRef:
        key: fizzy
        property: SMTP_ADDRESS
    - secretKey: SMTP_PORT
      remoteRef:
        key: fizzy
        property: SMTP_PORT
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: fizzy
        property: SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: fizzy
        property: SMTP_PASSWORD
    - secretKey: SMTP_DOMAIN
      remoteRef:
        key: fizzy
        property: SMTP_DOMAIN
