apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "fizzy.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: fizzy
        property: SECRET_KEY_BASE
