postgres:
  clusterName: haymaker-postgres
  database: haymaker
  owner: haymaker
  imageName: ghcr.io/cloudnative-pg/postgresql:17.10-system-trixie
  storage:
    storageClass: local-path
    size: 2Gi
  backup:
    enabled: true
    destinationPath: s3://cnpg-backups/haymaker-postgres
    endpointURL: http://10.77.77.190:9000
    secretName: cnpg-backup-s3
    onepasswordItem: synology-rustfs
    retentionPolicy: "30d"
    schedule: "0 10 4 * * *"

onepassword:
  postgresItem: haymaker-postgres
  appItem: haymaker
  ghcrItem: haymaker-ghcr

haymaker:
  fullnameOverride: haymaker
  imagePullSecrets:
    - name: haymaker-ghcr
  api:
    existingSecret: haymaker-env
    image:
      repository: ghcr.io/nezdemkovski/haymaker
      tag: "0.3.0"
      digest: sha256:aa15114dc08dd3ff5452d3d6c02ae772500cab9314173eaa5b05a4ea69c4103d
  frontend:
    image:
      repository: ghcr.io/nezdemkovski/haymaker-frontend
      tag: "0.3.0"
      digest: sha256:abadba3bcb897da44b9a787ab2376ac3a77122db4a47e4995fb90f525a2054be
