image:
  repository: deadair/deadair
  tag: "0.24.0@sha256:057275cadc968fdea29b7fe4f5d5b1815eaebf7c502a77f9a74d74f090cfbd31"
redis:
  image:
    repository: redis
    tag: "8.2.1-alpine@sha256:987c376c727652f99625c7d205a1cba3cb2c53b92b0b62aade2bd48ee1593232"
baseUrl: https://radio.nezdemkovski.cloud
timezone: Europe/Istanbul
existingSecret: deadair-runtime
persistence:
  storageClass: local-path
  size: 20Gi
resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 4Gi
