image:
  repository: deadair/deadair
  tag: "0.32.0@sha256:4cdee01c4aeb34a1f4478c51be4f554320a218265c79d97d084d9491bd19f523"
redis:
  image:
    repository: redis
    tag: "8.10.2-alpine@sha256:72cedd9603038893af961e90ac5e1a1a0d8377d5e338dbdad8fe284ea25de18f"
baseUrl: https://radio.nezdemkovski.cloud
timezone: Europe/Istanbul
existingSecret: deadair-runtime
persistence:
  storageClass: local-path
  size: 20Gi
resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 4Gi
