---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: auth
  namespace: auth
spec:
  interval: 1h0m0s
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  provider: generic
  ref:
    tag: 0.2.49
  url: oci://ghcr.io/nezdemkovski/charts/auth
