apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-env
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-env
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: forgejo
        property: username
    - secretKey: password
      remoteRef:
        key: forgejo
        property: password
    - secretKey: FORGEJO__server__DOMAIN
      remoteRef:
        key: forgejo
        property: FORGEJO__server__DOMAIN
    - secretKey: FORGEJO__server__ROOT_URL
      remoteRef:
        key: forgejo
        property: FORGEJO__server__ROOT_URL
    - secretKey: FORGEJO__server__SSH_DOMAIN
      remoteRef:
        key: forgejo
        property: FORGEJO__server__SSH_DOMAIN
