---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: amela-application
  namespace: amela
spec:
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
  image: ghcr.io/amela-io/application
  interval: 15m0s
  secretRef:
    name: amela-ghcr
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: amela-backend
  namespace: amela
spec:
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
  image: ghcr.io/amela-io/backend
  interval: 15m0s
  secretRef:
    name: amela-ghcr
