---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: amela-application
  namespace: amela
spec:
  image: ghcr.io/amela-io/application
  interval: 15m0s
  secretRef:
    name: amela-ghcr
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: amela-application
  namespace: amela
spec:
  digestReflectionPolicy: Always
  imageRepositoryRef:
    name: amela-application
  interval: 15m0s
  policy:
    semver:
      range: '>=0.1.15 <0.2.0'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: amela-backend
  namespace: amela
spec:
  image: ghcr.io/amela-io/backend
  interval: 15m0s
  secretRef:
    name: amela-ghcr
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: amela-backend
  namespace: amela
spec:
  digestReflectionPolicy: Always
  imageRepositoryRef:
    name: amela-backend
  interval: 15m0s
  policy:
    semver:
      range: '>=0.1.12 <0.2.0'
