apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  template:
    metadata:
      annotations:
        homelab.nezdemkovski.cloud/config-revision: {{ .Values.configRevision | quote }}
      labels:
        app.kubernetes.io/name: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - tunnel
            - --no-autoupdate
            - --loglevel
            - {{ .Values.logLevel }}
            - --metrics
            - {{ .Values.metrics.address }}:{{ .Values.metrics.port }}
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
          livenessProbe:
            httpGet:
              path: /ready
              port: metrics
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: credentials
              mountPath: /etc/cloudflared/credentials
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: cloudflared-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: credentials
          secret:
            secretName: {{ .Values.credentials.secretName }}
