apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.credentials.secretName }}
spec:
  refreshInterval: {{ .Values.credentials.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.credentials.externalSecret.secretStore.kind }}
    name: {{ .Values.credentials.externalSecret.secretStore.name }}
  target:
    name: {{ .Values.credentials.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: {{ .Values.credentials.externalSecret.remoteRef.key }}
        property: {{ .Values.credentials.externalSecret.remoteRef.property }}
