apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: tigpt6fc442bdsosxfljhv37a4
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          key: token
          namespace: external-secrets
