apiVersion: v2
name: openmarkers-stack
description: OpenMarkers homelab stack
type: application
version: 0.1.0
dependencies:
  - name: openmarkers
    version: 0.1.18
    repository: oci://ghcr.io/nezdemkovski/charts
